joint_limits:

    left_wheel:
      has_position_limits: true
      min_position: -10000.0
      max_position: 10000.0
      has_velocity_limits: true
      max_velocity: 500.0
      has_acceleration_limits: true
      max_acceleration: 10.0
      has_jerk_limits: true
      max_jerk: 200.0
      has_effort_limits: true
      max_effort: 100.0

    right_wheel:
      has_position_limits: true
      min_position: -10000.0
      max_position: 10000.0
      has_velocity_limits: true
      max_velocity: 500.0
      has_acceleration_limits: true
      max_acceleration: 10.0
      has_jerk_limits: true
      max_jerk: 200.0
      has_effort_limits: true
      max_effort: 100.0
